site_name: text-grade
theme:
  name: material
  features:
    - content.code.annotate
    - content.tooltips
    - navigation.sections
    - navigation.top
    - toc.integrate
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/amenezes/text-grade
repo_name: text-grade
nav:
- Home: index.md
