blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: https://github.com/amenezes/text-grade
    about: See if the project documentation or any other issue can help you to solve your doubt or problem before.
